class Config:
    STYLE = [":/style/style.json"]

    DONATIONS_WIDGET = "DONATIONS_WIDGET"
    DONATIONS_WIDGET_INDEX = 0
    CASES_TYPES_WIDGET = "CASES_TYPES_WIDGET"
    CASES_TYPES_WIDGET_INDEX = 4
    INVOICES_WIDGET = "INVOICES_WIDGET"
    INVOICES_WIDGET_INDEX = 2
    CASES_WIDGET = "CASES_WIDGET"
    CASES_WIDGET_INDEX = 1
    STORAGE_WIDGET = "STORAGE_WIDGET"
    STORAGE_WIDGET_INDEX = 5

    widgetIndices = {
        DONATIONS_WIDGET: DONATIONS_WIDGET_INDEX,
        CASES_TYPES_WIDGET: CASES_TYPES_WIDGET_INDEX,
        INVOICES_WIDGET: INVOICES_WIDGET_INDEX,
        CASES_WIDGET: CASES_TYPES_WIDGET_INDEX,
        STORAGE_WIDGET: STORAGE_WIDGET_INDEX,
    }
