class Config:
    DONATIONS_WIDGET = "DONATIONS_WIDGET"
    DONATIONS_WIDGET_INDEX = 0
    CASES_TYPES_WIDGET = "CASES_TYPES_WIDGET"
    CASES_TYPES_WIDGET_INDEX = 4
    INVOICES_WIDGET = "INVOICES_WIDGET"
    INVOICES_WIDGET_INDEX = 2

    widgetIndices = {
        DONATIONS_WIDGET: DONATIONS_WIDGET_INDEX,
        CASES_TYPES_WIDGET: CASES_TYPES_WIDGET_INDEX,
        INVOICES_WIDGET: INVOICES_WIDGET_INDEX,
    }
